<?php

namespace AiContextBundle\Tests\Generator;

use PHPUnit\Framework\TestCase;
use AiContextBundle\Generator\AbstractContextGenerator;


class AbstractContextGeneratorTest extends TestCase
{
    private function createDummyGenerator(): AbstractContextGenerator
    {
        return new class extends AbstractContextGenerator {
            public function generate(): array
            {
                return [];
            }

            public function findClasses(array $paths): array
            {
                return parent::findClasses($paths); // TODO: Change the autogenerated stub
            }

            public function getClassFromFile(string $filePath): ?string
            {
                return parent::getClassFromFile($filePath);
            }
        };
    }

    public function testFindClassesReturnsValidClassNames()
    {
        $generator = $this->createDummyGenerator();

        $classes = $generator->findClasses([
            dirname(__DIR__) . '/src/Command'
        ]);

        $this->assertIsArray($classes);
        $this->assertNotEmpty($classes);

        $this->assertContains('AiContextBundle\Command\GenerateAiContextCommand', $classes);
    }

    public function testGetClassFromInvalidFileReturnsNull()
    {
        $generator = $this->createDummyGenerator();

        $fakeFile = tempnam(sys_get_temp_dir(), 'test');
        file_put_contents($fakeFile, '<?php echo "no class here";');

        $class = $generator->getClassFromFile($fakeFile);

        $this->assertNull($class);

        unlink($fakeFile);
    }
}
