services:
    AiContextBundle\Command\:
        resource: '../src/Command'
        tags: ['console.command']
        autowire: true
        autoconfigure: true

    AiContextBundle\Generator\:
        resource: '../src/Generator'
        autowire: true
        autoconfigure: true
