services:
    AiContextBundle\Command\:
        resource: '../src/Command'
        tags: [ 'console.command' ]
        autowire: true
        autoconfigure: true

    AiContextBundle\Builder\:
        resource: '../src/Builder'
        autowire: true
        autoconfigure: true

    AiContextBundle\Generator\:
        resource: '../src/Generator'
        autowire: true
        autoconfigure: true

    AiContextBundle\Generator\EntityContextGenerator:
        arguments:
            $entityPaths: '%ai_context.paths.entities%'
            $doctrine: '@doctrine'

    AiContextBundle\Generator\ServiceContextGenerator:
        arguments:
            $servicePaths: '%ai_context.paths.services%'

    AiContextBundle\Generator\ControllerContextGenerator:
        arguments:
            $controllerPaths: '%ai_context.paths.controllers%'

    AiContextBundle\Generator\RepositoryContextGenerator:
        arguments:
            $repositoryPaths: '%ai_context.paths.repositories%'

    AiContextBundle\Generator\EventContextGenerator:
        arguments:
            $eventPaths: '%ai_context.paths.events%'

    AiContextBundle\Service\ChecksumService:
        arguments:
            $checksumFile: '%ai_context.output_dir_checksum%'
